### ISSUE TITLE
Implement statistics tracking

### ISSUE THREAD

**Issue by iarna** [npm/npm#12529]
We don't know how people use npm. We don't know how well it works for them. Not really. Our ways of hear our users, here, twitter, the web, only reach a tiny fraction of our users. We don't know how fast or slow installs typically are, nor how big they are, nor how often folks see errors.

In order to work toward answering these questions so that we can make better decisions about the tool, we are going to start adding some metrics. Initially we will just track, on an opt-in basis, how often installs end in error. This is intentionally small, both so that implementation on our part will be easy, but also so that the privacy implications will be clear.
### The work to be done on this project is:
- [ ] For users who opt in (by adding a configuration option), start recording how many times installs succeed or end in an error in a file in the cache (eg, something like `CACHEDIR/metrics.json`).
  
  When npm completes:
  - If a metrics file exists, increment the successful or failed installs and update the `to` time.
  - If a metrics file does not exist, create a new stats file with a new `metricId` associated with it and fresh `from` and `to` times.

---
- [ ] Add a new API to [`npm-registry-client`](https://github.com/npm/npm-registry-client/issues/138) and the [registry itself](https://github.com/npm/registry/issues/11) for sending stats information to a registry.

---
- [ ] Using the new API, send stats data to the registry.
  #### When starting a new install command:
  - If the metric file exists:
    - Call `sendAnonymousCLIMetrics` to send the metrics to the default registry. If the request fails or does not complete before npm exits the metrics file should be left in place. If the request succeeds then the current metrics file should be removed.

_We may not be able to support 0.8, as it can't `unref` sockets (AFAIK)._

**Comment by lazywithclass** [comment]
I am willing to help with this, do you have some more details / some key points as a result of the CLI team meeting?

**Comment by iarna** [comment]
Sure, I need to finish updating these issues with the latest round of discussions internally, but the place to start is → https://github.com/npm/npm-registry-client/issues/138

When I do that update, I'll tag you over on that issue.

**Comment by lazywithclass** [comment]
Many thanks @iarna

**Comment by lazywithclass** [comment]
@iarna I've just committed (https://github.com/lazywithclass/npm/commit/e58df224b5bfca0b64652ce7aa84c4caf3667a5f) my idea on how to collect the required metrics. It's just a stub, to see if I'm going in the right direction.

Could you please have a look to see if this makes sense at all? :P

**Comment by iarna** [comment]
@lazywithclass Ahh, sorry about not getting back to you there.

I ended up implementing it as seen here:
https://github.com/npm/npm/pull/15084/commits/38e5c4fdddaa193afa05cf338e1e9850c73c5017

I had to go with a child process for submission as Node.js can be convinced to hang deep in it's networking layer with certain kinds of network problems, and those would hold the event loop open, stopping `npm` from exiting.

**Comment by lazywithclass** [comment]
@iarna no worries, thanks for the link. I will try to contribute in other issues!
